STROKE_SPACING = 2  # Расстояние между штрихами
FLASK_LENGTH_HALF = 40  # Длина колбы делённое на два
DISTANCE_FIRST_TO_END_FLASK = 31.5  # Расстояние от первого штриха до конца колбы
DISTANCE_CENTER_TO_FIRST_STROKE = 8.5  # Расстояние от центра колбы до первого штриха
NUMBER_OF_ARC_SECONDS_ONE_STROKE = 4  # Количество угловых секунд на одном штрихе

REL_FROM_CENTER_TO_FIRST_HATCH = FLASK_LENGTH_HALF / DISTANCE_CENTER_TO_FIRST_STROKE  # Отношение от центра до первого штриха
REL_BETWEEN_HATCH_TO_END = DISTANCE_FIRST_TO_END_FLASK / STROKE_SPACING  # Отношение между штрихами до конца
COUNT_ARC_SECOND = 0.314311216  # Количество угловых секунд в штрихе

options_dict: dict = {
    "STROKE_SPACING": STROKE_SPACING,
    "FLASK_LENGTH_HALF": FLASK_LENGTH_HALF,
    "DISTANCE_FIRST_TO_END_FLASK": DISTANCE_FIRST_TO_END_FLASK,
    "DISTANCE_CENTER_TO_FIRST_STROKE": DISTANCE_CENTER_TO_FIRST_STROKE,
    "NUMBER_OF_ARC_SECONDS_ONE_STROKE": NUMBER_OF_ARC_SECONDS_ONE_STROKE,
    "REL_FROM_CENTER_TO_FIRST_HATCH": REL_FROM_CENTER_TO_FIRST_HATCH,
    "REL_BETWEEN_HATCH_TO_END": REL_BETWEEN_HATCH_TO_END,
    "COUNT_ARC_SECOND": COUNT_ARC_SECOND,
}
